import { execSync } from "node:child_process";
import { logPhase, logError, logSuccess, logInfo, logWarning } from "../utils/logger.js";
import { loadConfig } from "../utils/config.js";
import { addFeature, updateFeature } from "../utils/features.js";
import { appendProgress } from "../utils/progress.js";
import { fetchIssue, postComment, getRepoInfo } from "../utils/github.js";
import { analyzeIssue } from "../agents/issue-analyzer.js";
import { runGeneratorAgent } from "../agents/generator.js";
import { runEvaluatorAgent } from "../agents/evaluator.js";

export async function runMaintain(cwd: string, issueNumber: number): Promise<void> {
  logPhase(`Maintenance: Issue #${issueNumber}`);

  const config = loadConfig(cwd);
  const repoInfo = getRepoInfo(cwd);

  // Fetch issue
  const issue = await fetchIssue(repoInfo, issueNumber);

  // Safety: Check allowed authors
  if (config.allowedIssueAuthors.length > 0) {
    if (!config.allowedIssueAuthors.includes(issue.author)) {
      logError(`Issue author "${issue.author}" is not in the allowedIssueAuthors list.`);
      process.exit(1);
    }
  }

  // Analyze issue
  logInfo("Analyzing issue...");
  const analysis = await analyzeIssue(cwd, issue);

  if (analysis.needsClarification) {
    logWarning("Issue is too unclear — posting follow-up question...");
    await postComment(
      repoInfo,
      issueNumber,
      `🤖 **Automated Analysis**\n\nThis issue needs more details:\n\n${analysis.clarificationMessage}\n\n---\n*Generated by sveltekit-orchestrator*`,
    );
    process.exit(0);
  }

  if (!analysis.feature) {
    logError("Issue analysis did not produce a feature.");
    process.exit(1);
  }

  // Create feature branch
  const branchName = `auto/issue-${issueNumber}`;
  logInfo(`Creating feature branch: ${branchName}`);
  try {
    execSync(`git checkout -b ${branchName}`, { cwd, stdio: "pipe" });
  } catch {
    // Branch might already exist
    execSync(`git checkout ${branchName}`, { cwd, stdio: "pipe" });
  }

  // Add feature to features.json
  addFeature(cwd, analysis.feature);

  // Build loop
  const feature = analysis.feature;
  let attempt = 0;
  let passed = false;
  let evalFeedback: string | undefined;

  const timeout = setTimeout(() => {
    logError(`Timeout after ${config.timeoutMinutes} minutes`);
    process.exit(1);
  }, config.timeoutMinutes * 60 * 1000);
  timeout.unref();

  while (attempt < config.maxRetriesPerFeature && !passed) {
    attempt++;
    logInfo(`Generator/Evaluator attempt ${attempt}/${config.maxRetriesPerFeature}`);

    try {
      await runGeneratorAgent(cwd, feature, evalFeedback);
    } catch (error) {
      const errMsg = error instanceof Error ? error.message : String(error);
      logError(`Generator crashed: ${errMsg}`);
      appendProgress(cwd, `💥 ${feature.id} (Issue #${issueNumber}) — GENERATOR CRASH (attempt ${attempt})`);
      evalFeedback = `Generator crashed with error: ${errMsg}. Please fix the issue and try again.`;
      continue;
    }

    try {
      const evalResult = await runEvaluatorAgent(cwd, feature);

      if (evalResult.verdict === "PASS") {
        passed = true;
        updateFeature(cwd, feature.id, { passes: true });
        appendProgress(cwd, `✅ ${feature.id} (Issue #${issueNumber}) — PASS (attempt ${attempt})`);
      } else {
        evalFeedback = evalResult.report;
        appendProgress(cwd, `❌ ${feature.id} (Issue #${issueNumber}) — FAIL (attempt ${attempt})`);
      }
    } catch (error) {
      const errMsg = error instanceof Error ? error.message : String(error);
      logError(`Evaluator crashed: ${errMsg}`);
      appendProgress(cwd, `💥 ${feature.id} (Issue #${issueNumber}) — EVALUATOR CRASH (attempt ${attempt})`);
      evalFeedback = `Evaluator crashed with error: ${errMsg}. There may be build or runtime errors to fix.`;
    }
  }

  clearTimeout(timeout);

  if (passed) {
    // Commit + Push
    logInfo("Committing and pushing changes...");
    execSync("git add -A", { cwd, stdio: "pipe" });
    execSync(
      `git commit -m "feat: resolve #${issueNumber} — ${feature.title}"`,
      { cwd, stdio: "pipe" },
    );
    execSync(`git push -u origin ${branchName}`, { cwd, stdio: "pipe" });

    // Comment on issue
    const acList = feature.acceptance_criteria.map((ac) => `- ✅ ${ac}`).join("\n");
    await postComment(
      repoInfo,
      issueNumber,
      `🤖 **Automatically implemented**\n\nAll acceptance criteria tested and passed:\n\n${acList}\n\nBranch: \`${branchName}\`\n\n---\n*Generated by sveltekit-orchestrator*`,
    );

    logSuccess(`Issue #${issueNumber} resolved successfully. Branch: ${branchName}`);
  } else {
    // Comment failure on issue
    await postComment(
      repoInfo,
      issueNumber,
      `🤖 **Automated implementation failed**\n\nAfter ${attempt} attempts, the issue could not be fully resolved.\n\nLast eval report:\n\`\`\`\n${evalFeedback?.slice(0, 2000) ?? "No report available"}\n\`\`\`\n\n---\n*Generated by sveltekit-orchestrator*`,
    );

    logError(`Issue #${issueNumber} could not be resolved after ${attempt} attempts.`);
    process.exit(1);
  }
}
